<?php
//This is a test
class JConfig {
	var $offline = '0';
	var $editor = 'wysiwygPro3';
	var $list_limit = '20';
	var $helpurl = 'http://help.joomla.org';
	var $debug = '0';
	var $debug_lang = '0';
	var $sef = '1';
	var $sef_rewrite = '0';
	var $sef_suffix = '0';
	var $feed_limit = '10';
	var $feed_email = 'author';
	var $secret = 'VHPiZT2LLmaRsEIB';
	var $gzip = '0';
	var $error_reporting = '-1';
	var $xmlrpc_server = '0';
	var $log_path = '/var/www/healthcommcore.org/logs';
	var $tmp_path = '/var/www/healthcommcore.org/tmp';
	var $live_site = '';
	var $force_ssl = '0';
	var $offset = '0';
	var $caching = '0';
	var $cachetime = '15';
	var $cache_handler = 'file';
	var $memcache_settings = array();
	var $ftp_enable = '0';
	var $ftp_host = '127.0.0.1';
	var $ftp_port = '31957';
	var $ftp_user = 'healthcommcore_ftp';
	var $ftp_pass = 'ci5frveh';
	var $ftp_root = 'healthcommcore.org';
	var $dbtype = 'mysql';
	var $host = 'localhost';
	var $user = 'hccstudio';
	var $db = 'hccstudio';
	var $dbprefix = 'jos_';
	var $mailer = 'mail';
	var $mailfrom = 'dave_rothfarb@dfci.harvard.edu';
	var $fromname = 'HCCStudio';
	var $sendmail = '/usr/sbin/sendmail';
	var $smtpauth = '0';
	var $smtpsecure = 'none';
	var $smtpport = '25';
	var $smtpuser = '';
	var $smtppass = '';
	var $smtphost = 'localhost';
	var $MetaAuthor = '1';
	var $MetaTitle = '1';
	var $lifetime = '90';
	var $session_handler = 'database';
	var $password = 'hccstudio';
	var $sitename = 'Health Communication Core';
	var $MetaDesc = 'The Health Communication Core (HCC) offers professional creative services to researchers, clinicians, and others from Dana-Farber/Harvard Cancer Center (DF/HCC), Dana-Farber Cancer Institute (DFCI), and other medical and research institutions.';
	var $MetaKeys = 'health communication core, health communication, health, communication, design, writing, logo, print, graphic, editing, web, development, intervention, ECHO Lab, Vish Viswanath, Catherine Coleman, Eugenie Olson, Adam Gerberick, Cori Couture, Lauren Becker, Dave Rothfarb, HCC’s Scientific Advisory Committee, Karen Emmons, PhD, Karen Burns White, Mary Cooley, PhD, APRN, BC, Lisa DiGianni, PhD, Lisa Diller, MD, Karen Donelan, EdM, ScD, Lindsay Frazier, MD, ScM, Matthew Gillman, MD, SM, Elizabeth Gonzalez-Suarez, Eileen Duffey Lind, RN, MSN, CPNP, Steven Joffe, MD, MPH, Kenneth Miller, MD, Ann Partridge, MD, MPH, Kim, Sprunck-Harrild, MSW, MPH, Sapna Syngal, MD, MPH, Lorraine Wallace, MPH, Joanne Wolfe, MD, MPH';
	var $offline_message = 'This site is down for maintenance. Please check back again soon.';
}
?>
